name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gtest manually
      run: |
        sudo apt-get install -y libgtest-dev cmake
        mkdir -p $HOME/build
        cd $HOME/build
        sudo cmake /usr/src/googletest/googletest
        sudo make
        sudo cp lib/libgtest* /usr/lib/
        cd ..
        sudo rm -rf build
        sudo mkdir /usr/local/lib/googletest
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/googletest/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/googletest/libgtest_main.a      
    - name: Install dependencies
      run: sudo apt-get install -y libeigen3-dev
    - name: make tests
      run: make tests
