name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gtest
    - uses: MarkusJx/googletest-installer@v1.1
    - name: install dependencies
      run: sudo apt update && sudo apt install -y libeigen3-dev googletest openmpi-bin
    - name: make
      run: make
    - name: make tests
      run: make tests
